name: attendance_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  mobile_scanner: ^4.0.0
  qr_flutter: ^4.1.0
  table_calendar: ^3.0.9
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  equatable: ^2.0.7
  rxdart: ^0.28.0
  fl_chart: ^0.69.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
dependency_overrides:
  win32: ^5.14.0
  ffi: ^2.1.4